// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "blog": Application Media Types
//
// Command:
// $ goagen
// --design=git.si-media.biz/takutoarao/start/design
// --out=$(GOPATH)/src/git.si-media.biz/takutoarao/start
// --version=v1.2.0-dirty

package client

import (
	"github.com/goadesign/goa"
	"net/http"
)

// A blog of wine (default view)
//
// Identifier: application/vnd.goa.example.blog+json; view=default
type GoaExampleBlog struct {
	// API href for making requests on the blog
	Href string `form:"href" json:"href" xml:"href"`
	// Unique blog ID
	ID int `form:"id" json:"id" xml:"id"`
	// Name of wine
	Name string `form:"name" json:"name" xml:"name"`
}

// Validate validates the GoaExampleBlog media type instance.
func (mt *GoaExampleBlog) Validate() (err error) {

	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}

// DecodeGoaExampleBlog decodes the GoaExampleBlog instance encoded in resp body.
func (c *Client) DecodeGoaExampleBlog(resp *http.Response) (*GoaExampleBlog, error) {
	var decoded GoaExampleBlog
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
