// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "blog": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=git.si-media.biz/takutoarao/start/design
// --out=$(GOPATH)/src/git.si-media.biz/takutoarao/start
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// BlogHref returns the resource href.
func BlogHref(blogID interface{}) string {
	paramblogID := strings.TrimLeftFunc(fmt.Sprintf("%v", blogID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/blogs/%v", paramblogID)
}
