// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "blog": Application User Types
//
// Command:
// $ goagen
// --design=git.si-media.biz/takutoarao/start/design
// --out=$(GOPATH)/src/git.si-media.biz/takutoarao/start
// --version=v1.2.0-dirty

package app
